global:
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'm176147512@163.com'
  smtp_auth_username: 'm176147512@163.com'
  smtp_auth_password: '123456'

route:
  receiver: 'default-receiver'
  group_by: ['appid','service','title']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 2h
  routes:
  - receiver: 'receiver-1'
    group_wait: 10s
    match_re:
      appid: test2

receivers:
- name: default-receiver
  email_configs:
  - to: 'm176147512@163.com'
    require_tls: false
- name: receiver-1
  email_configs:
  - to: '473132488@qq.com'
    require_tls: false
templates:
- 'D:\alertmanager-0.15.3.windows-amd64\template\*.tmpl'