global:
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'm176147512@163.com'
  smtp_auth_username: 'm176147512@163.com'
  smtp_auth_password: '123456'

templates:
- 'D://alertmanager-0.15.3.windows-amd64/alertemp.tmpl'

route:
  receiver: 'default-receiver'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 4m
  routes:
  - receiver: 'database'
    group_wait: 10s
    match_re:
      service: mysql|cassandra
receivers:
- name: default-receiver
  email_configs:
  - to: 'm176147512@163.com'
- name: database
  email_configs:
  - to: '412312@qq.com'